services:
  mathz_app:
    build:
      context: .
      dockerfile: DockerfileDev
    ports:
      - "9002:92"
    volumes:
      - .:/var/www

  mathz_database:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: mathz_database
      MYSQL_ROOT_PASSWORD: leagueofdraven
    ports:
      - "3307:3306"

  mathz_websocker:
    container_name: soketi
    image: quay.io/soketi/soketi:1.4-16-debian
    restart: unless-stopped
    ports:
      - '${SOKETI_PORT:-6001}:6001'
      - '${SOKETI_METRICS_SERVER_PORT:-9601}:9601'
    environment:
      - SOKETI_ADAPTER_DRIVER=redis
      - SOKETI_DEBUG=${PUSHER_DEBUG:-1}
      - SOKETI_DEFAULT_APP_ID=${PUSHER_APP_ID:-some-id}
      - SOKETI_DEFAULT_APP_KEY=${PUSHER_APP_KEY:-app-key}
      - SOKETI_DEFAULT_APP_SECRET=${PUSHER_APP_SECRET:-some-app-secret}
      - PUSHER_HOST=${PUSHER_HOST:-127.0.0.1}
      - PUSHER_PORT= ${PUSHER_PORT:-6001}
      - PUSHER_SCHEME=${PUSHER_SCHEME:-http}
      - METRICS_SERVER_PORT=${SOKETI_METRICS_SERVER_PORT:-9601}
      - DEFAULT_APP_ENABLE_CLIENT_MESSAGES=${DEFAULT_APP_ENABLE_CLIENT_MESSAGES:-false}
      - SOKETI_DB_REDIS_HOST=${SOKETI_DB_REDIS_HOST:-redis}
      - SOKETI_DB_REDIS_PORT=${SOKETI_DB_REDIS_PORT:-6379}
      - SOKETI_DB_REDIS_DB=${SOKETI_DB_REDIS_DB:-0}
      - SOKETI_DB_REDIS_USERNAME=${SOKETI_DB_REDIS_USERNAME:-}
      - SOKETI_DB_REDIS_PASSWORD=${SOKETI_DB_REDIS_PASSWORD:-}
      - SOKETI_DB_REDIS_KEY_PREFIX=${SOKETI_DB_REDIS_KEY_PREFIX:-}
